import { z } from "zod";
import { dayOfWeekSchema, workoutTypeSchema } from "./enums";
import { setLogEntrySchema } from "./session";

const strengthExerciseSchema = z.object({
  name: z.string(),
  setsReps: z.string(),
  isMainLift: z.boolean().optional(),
  notes: z.string().optional(),
});

const prescriptionSchema = z.object({
  distanceMiles: z.number().optional(),
  durationMin: z.number().optional(),
  quality: z.enum(["easy", "tempo", "intervals", "long"]).optional(),
  reducedVolume: z.boolean().optional(),
  notes: z.string().optional(),
  // Strength-session fields (LIFT-type workouts generated by strength-engine)
  sessionName: z.string().optional(),
  displayName: z.string().optional(),
  block: z.string().optional(),
  weekInCycle: z.number().int().optional(),
  isDeloadWeek: z.boolean().optional(),
  exercises: z.array(strengthExerciseSchema).optional(),
});

// Exported (not module-private) so other output schemas needing the same
// per-workout shape — e.g. schemas/overview.ts's full plan view — reuse it
// instead of redefining it.
export const plannedWorkoutSchema = z.object({
  id: z.string(),
  day: dayOfWeekSchema,
  type: workoutTypeSchema,
  prescription: prescriptionSchema,
});

const sessionLogSchema = z.object({
  id: z.string(),
  date: z.date(),
  type: workoutTypeSchema,
  distanceMiles: z.number().nullable(),
  durationMin: z.number(),
  rpe: z.number(),
  notes: z.string().nullable(),
  plannedWorkoutId: z.string().nullable(),
  setLog: z.array(setLogEntrySchema).nullable(),
});

// Long-run distance only, on both sides. Easy and quality runs are prescribed
// by duration, so they have no planned distance to compare a logged one
// against — including logged distance for them here would show every week as a
// large overshoot against a planned number that never counted those runs.
const weeklyMileageSchema = z.object({
  weekNumber: z.number().int(),
  plannedMiles: z.number(),
  // Null for weeks that haven't happened yet, so the rest of the plan doesn't
  // render as a run of zeroes that reads like missed training. A past week
  // with no logged long run is a real 0 — that's the adherence signal.
  actualMiles: z.number().nullable(),
});

// Shared plan-meta shape — same fields getDashboard and getPlanOverview
// both compute per plan (see router.ts's computePlanMeta helper).
export const planMetaSchema = z.object({
  id: z.string(),
  raceDate: z.date(),
  startDate: z.date(),
  totalWeeks: z.number().int(),
  currentWeek: z.number().int(),
  phase: z.enum(["base", "build", "peak", "taper"]),
  feasibilityWarning: z.string().nullable(),
  strengthWarning: z.string().nullable(),
  injuryWarning: z.string().nullable(),
});

export const dashboardOutputSchema = z.object({
  plan: planMetaSchema.nullable(),
  plannedWorkouts: z.array(plannedWorkoutSchema),
  sessionLogs: z.array(sessionLogSchema),
  // Null when sessions were logged this week but none of them recorded a
  // distance — distinct from 0, which means nothing was logged at all. Distance
  // is optional on the log form and most runs are prescribed by duration, so
  // "not measured in miles" is a normal state, not a missing value.
  weeklyMileageTotal: z.number().nullable(),
  weeklyMileageHistory: z.array(weeklyMileageSchema),
});

export type DashboardOutput = z.infer<typeof dashboardOutputSchema>;
