import { z } from "zod";
import { dayOfWeekSchema, workoutTypeSchema } from "./enums";
import { setLogEntrySchema } from "./session";

const strengthExerciseSchema = z.object({
  name: z.string(),
  setsReps: z.string(),
  isMainLift: z.boolean().optional(),
  notes: z.string().optional(),
});

const prescriptionSchema = z.object({
  distanceMiles: z.number().optional(),
  durationMin: z.number().optional(),
  quality: z.enum(["easy", "tempo", "intervals", "long"]).optional(),
  reducedVolume: z.boolean().optional(),
  notes: z.string().optional(),
  // Strength-session fields (LIFT-type workouts generated by strength-engine)
  sessionName: z.string().optional(),
  displayName: z.string().optional(),
  block: z.string().optional(),
  weekInCycle: z.number().int().optional(),
  isDeloadWeek: z.boolean().optional(),
  exercises: z.array(strengthExerciseSchema).optional(),
});

const plannedWorkoutSchema = z.object({
  id: z.string(),
  day: dayOfWeekSchema,
  type: workoutTypeSchema,
  prescription: prescriptionSchema,
});

const sessionLogSchema = z.object({
  id: z.string(),
  date: z.date(),
  type: workoutTypeSchema,
  distanceMiles: z.number().nullable(),
  durationMin: z.number(),
  rpe: z.number(),
  notes: z.string().nullable(),
  plannedWorkoutId: z.string().nullable(),
  setLog: z.array(setLogEntrySchema).nullable(),
});

const weeklyMileageSchema = z.object({
  weekNumber: z.number().int(),
  plannedMiles: z.number(),
  actualMiles: z.number(),
});

export const dashboardOutputSchema = z.object({
  plan: z
    .object({
      id: z.string(),
      raceDate: z.date(),
      startDate: z.date(),
      totalWeeks: z.number().int(),
      currentWeek: z.number().int(),
      phase: z.enum(["base", "build", "peak", "taper"]),
    })
    .nullable(),
  plannedWorkouts: z.array(plannedWorkoutSchema),
  sessionLogs: z.array(sessionLogSchema),
  weeklyMileageTotal: z.number(),
  weeklyMileageHistory: z.array(weeklyMileageSchema),
});

export type DashboardOutput = z.infer<typeof dashboardOutputSchema>;
